apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streamshub-console

resources:
  - https://github.com/streamshub/console/releases/download/0.11.0/streamshub-console-operator.yaml
  - namespace.yaml

patches:
  - target:
      kind: ClusterRoleBinding
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: streamshub-console
  - target:
      kind: RoleBinding
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: streamshub-console
