apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/refs/tags/0.49.0/examples/kafka/kafka-single-node.yaml
  - namespace.yaml

patches:
  - target:
      kind: Kafka
    patch: |-
      - op: replace
        path: /metadata/name
        value: test-cluster
  - target:
      kind: KafkaNodePool
    patch: |-
      - op: replace
        path: /metadata/labels/strimzi.io~1cluster
        value: test-cluster

